---
- name: Experiment with IP addressing
  connection: local
  hosts: localhost
  gather_facts: false
  vars:
    ips:
      - 192.168.4.0
      - 10.25.1.1/32
      - 10.25.1.15/23
      - 1.1.1.1
  tasks:
    - name: Is this an IP
      debug:
        msg: '{{ item | ipaddr }}'
      loop: '{{ ips }}'
    - name: Show host IP addresses
      debug:
        msg: '{{ ips | ipaddr("address") }}'
    - name: Show private addresses
      debug:
        msg: '{{ ips | ipaddr("private") }}'
    - name: Show range of usable IPs from 10.25.1.15/23
      debug:
        msg: '{{ "10.25.1.15/23" | ipaddr("range_usable") }}'
    - name: Subtract 10 from the existing IP address
      debug:
        msg: '{{ item | ipmath(-10)}}'
      loop: '{{ ips }}'
    - name: Merge adjacent or overlapping subnets
      debug:
        msg: '{{ ["192.168.4.0/24", "192.168.5.0/24", "192.168.7.0/24"] | cidr_merge() }}'
