---
- name: Try variables
  connection: network_cli
  hosts: all
  gather_facts: false
  vars:


  tasks:
    - name: Create user using IOS user module
      ios_user:
        name: 
        configured_password: 
        state: present
      register: user_creation_module

    - debug:
        var: user_creation_module
