---
- name: Experiment with looping
  connection: local
  hosts: localhost
  gather_facts: false
  vars:
    username: kbreit
    password: p@ssw0rd
    vlans:
      - 10
      - 11
      - 12
      - 13
  tasks:
    - name: Use loop to create 4 SVIs
      ios_interface:
        name: 'GigabitEthernet1.{{ item }}'
      loop: vlans
      register: new_vlans
    - debug:
        var: new_vlans
