---
- name: Experiment with looping
  connection: network_cli
  hosts: all
  gather_facts: false
  vars:
    vlans:
      - 
      - 
      - 
      - 
  tasks:
    - name: Use loop to create 4 SVIs
      ios_interface:


      register: new_vlans
    - debug:
        var: new_vlans
